name: Build APK from ZIP

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 👇 Yaha apne zip ka naam set karo (jo aapne upload kiya hai)
      - name: Find & unzip project
        run: |
          set -e
          ZIP_FILE=$(ls -1 *.zip | head -n1)
          echo "Using ZIP: $ZIP_FILE"
          unzip -q "$ZIP_FILE"
          # top-level project dir (e.g., VIPNumberApp/)
          DIR=$(ls -d */ | grep -i vipnumberapp | head -n1 | tr -d '/')
          echo "PROJECT_DIR=$DIR" >> $GITHUB_ENV
          echo "Project dir: $DIR"
          ls -la "$DIR"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
          build-root-directory: ${{ env.PROJECT_DIR }}
          arguments: |
            :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VIPNumberApp-APK
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
